apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-gitops-app # Changed name
  namespace: jenkins-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-gitops-app # Changed name
  template:
    metadata:
      labels:
        app: spring-boot-gitops-app # Changed name
    spec:
      containers:
      - name: spring-app
        image: indu1999/spring-boot-gitops-app:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
