apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: jenkins-apps
spec:
  type: NodePort
  selector:
    app: spring-boot-app-gitops
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32085
