apiVersion: v1
kind: Service
metadata:
  name: spring-boot-gitops-service # Changed name
  namespace: jenkins-apps
spec:
  type: NodePort
  selector:
    app: spring-boot-gitops-app # Directs traffic to the new GitOps deployment
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32090 # New unique NodePort!
